export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCT_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const PRODUCTS_DETAIL_REQUEST = "PRODUCTS_DETAIL_REQUEST"
export const PRODUCTS_DETAIL_SUCCESS = "PRODUCTS_DETAIL_SUCCESS"
export const PRODUCTS_DETAIL_FAIL = "PRODUCTS_DETAIL_FAIL"

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"

export const RANDOM_PRODUCT_REQUEST = "RANDOM_PRODUCT_REQUEST"
export const RANDOM_PRODUCT_SUCCESS = "RANDOM_PRODUCT_SUCCESS"
export const RANDOM_PRODUCT_FAIL = "RANDOM_PRODUCT_FAIL"

export const ALL_ADMIN_PRODUCTS_REQUEST = "ALL_ADMIN_PRODUCTS_REQUEST"
export const ALL_ADMIN_PRODUCTS_SUCCESS = "ALL_ADMIN_PRODUCTS_SUCCESS"
export const ALL_ADMIN_PRODUCTS_FAIL = "ALL_ADMIN_PRODUCTS_FAIL"

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST"
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS"
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET"
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"